### PR TITLE
Include uBO specific filter list from within a main filter list

### PR DESCRIPTION
**Pull request by addisr**
New feature introduced in uBO v1.15.0. Simplifies future updates to filter rules.

To not break filters for uBO users we first **need** to create PR to gorhill/uBlock with updated filter.txt URL (and wait for it to merge first). I will do it if you are okay with this change. Please let me know.

### CODE REVIEW

**Comment by vobruba-martin** [comment]
Could you rebase, please?

**Comment by vobruba-martin** [comment]
Ah, I see your edit now.

I think we should do this change as follows for keeping backward compatibility as mush as possible:
1. In the first round we should update just the `filters.txt`
2. Create PR with changed URL to gorhill/uBlock
3. After some time when most of users have updated URL update `filters_ublock.txt` file

What do you think?

**Comment by addisr** [comment]
I have now updated only `filters.txt` and created `filters_ublock_only.txt` thats gonna be included for now and removed when URL gets updated. That way we are not going to break any rules for uBO users while waiting for URL update. What do you think?

**Comment by vobruba-martin** [comment]
Even better! Thanks!

**Pull request merged**
