### PR TITLE
A:`letemsvetemapplem.eu`

### PR DESCRIPTION
**Pull request by eporubin**
ads  all around the page:
image

### CODE REVIEW

**Comment by eporubin** [comment]
@mlnrDev Hi, just checked this domain and the filter proposed are still working can you merge please 🙏  Thank you in advance

**Comment by mlnrDev** [comment]
> @mlnrDev Hi, just checked this domain and the filter proposed are still working can you merge please 🙏 Thank you in advance

hi, can I ask what content/ad blocker you use? generally, if you use uBlock Origin, you should enable most of the default lists - ads on the website in question are already blocked by `EasyList` and `AdGuard - Ads`

**Comment by monzta** [comment]
I checked with ABP in Chrome with EasyList Czech and Slovak+EasyList enabled. And also with uBO with default lists and EasyList Czech and Slovak activated. I get these ads in both configs.

**Comment by monzta** [comment]
Can you reproduce the ads with my mentioned setups?

**Comment by mlnrDev** [comment]
> Can you reproduce the ads with my mentioned setups?

yep, can repro. enabling `AdGuard - Ads` gets rid of them

**Comment by monzta** [comment]
You are correct, ads are blocked in the AdGauard base list which is enabled by default in AdGuard. Not sure why they decided to block it there even though they also offer `EasyList Czech and Slovak` in the settings. 

So usually the way it works is that `EasyList` removes ads on English speaking websites. And then there are language specific lists that take care of non-English speaking websites. So If a site is in let's say German only, filters are added `EasyList Germany`. ABP selects the default filter list based on the language of the browser when installing it (just checked uBlock Origin and it does the same). 

Users that have their browser set to Slovak or Czech will end up using `EasyList Czech and Slovak` together with `EasyList`. I believe for all common ad blocking extension the idea is to remove all ads by default (in some cases depending if there is a filter lists that covers a particular language). In both cases (ABP and uBO) user will see ads on this site that was reported becaue there are no filters in `EasyList Czech and Slovak`. 

Of course you can enable `AdGuard - Ads` in the settings of uBO (there is no such setting in ABP), however most users don't change their settings. The right place for such filters would be in fact inside this filter list here so all Czeck and Slovak users benefit from it automatically.

**Pull request closed without merging**
