### PR TITLE
Update filters.txt

### PR DESCRIPTION
**Pull request by petersaly**
added filter for issue: 
https://github.com/tomasko126/easylistczechandslovak/issues/189

### CODE REVIEW

**Comment by petersaly** [comment]
@Aslanex pridal som filter ||tinypass.com
bude blokovat aj request buy.tinypass.com? Alebo je ina syntax v custom filters a ina ked to predam sem?

**Comment by Aslanex** [comment]
Jo, mělo by to blokovat i subdomény.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by petersaly** [comment]
Ano uz blokuje, len som bol nedockavy kym sa spravne aktualizuje filter v chrome

**Comment by petersaly** [comment]
vdaka

so 3. 11. 2018 o 22:51 Aslanex <notifications@github.com> napísal(a):

**Pull request merged**
