### PR TITLE
fix search.seznam.cz

### PR DESCRIPTION
**Pull request by MekliCZ**
this blocks everything in the left column except organic results

### CODE REVIEW

**Comment by addisr** [comment]
Yes, that's what it's supposed to do. Same way as Google Search paid results are being blocked.

**Comment by MekliCZ** [comment]
yeah, but most of these non-organic results aren't paid

**Comment by addisr** [comment]
Hm, for example when searching for "*televize*" you cant even see **any** search results until you scroll down (with full hd resolution). And (roughly) first half of visible content has green tag "*Reklama*". I ain't no expert but I'm pretty sure it's paid position => ads. Getting similar results for other generic searches. What non-paid + non-organic results are we talking about here?

**Comment by MekliCZ** [comment]
yeah, „reklama“ means ad, but non-organic results for „vtip“, „počasí“ etc. on desktop or name of politician (for example Miloš Zeman) or a place („česká spořitelna bankomat ládví“ = ATM of Česká spořitelna on Ládví) on phone aren't ads

**Comment by addisr** [comment]
Okay that's a good point. But instead of deleting this rule completely we should fix it. What about this:
```
search.seznam.cz,clanky.seznam.cz##div.Layout--left > div:not(:has([class*="Result"]))
search.seznam.cz,clanky.seznam.cz##div.Layout--left > div:has(.ZboziCategory)
```

**Comment by addisr** [comment]
Updated in https://github.com/tomasko126/easylistczechandslovak/commit/82bef7dbf951aff9572792dfaa6328b7b8e4831f. Thanks for report.

**Comment by MekliCZ** [comment]
This still hides some hints, for example the tennis one (query „kvitová“).

**Pull request closed without merging**
